# App Name
app_name: sicaf

# Deployer User and Groups
deployer_user: <your-user-name>
deployer_group: <your-user-group>

# Github Code's Repo URL
api_repo_url: https://github.com/altest-com/sicaf-api
spa_repo_url: https://github.com/altest-com/sicaf-spa

# Whether to build spa
build_spa: false

# App Directory
app_dir: '/home/{{ deployer_user }}/{{app_name}}'
app_api_dir: '{{app_dir}}/sicaf-api'
app_spa_dir: '{{app_dir}}/sicaf-spa'
app_spa_dist: '{{app_spa_dir}}/dist'
env_file: '{{ app_dir }}/.env.prod'

# DB Configuration
db_name: '{{ app_name }}'
db_user: '{{ deployer_user }}'
db_host: localhost
db_password: <your-db-password>

# Application Dependencies Setup
venv_root: '/home/{{ deployer_user }}/envs'
venv_dir: '{{ venv_root }}/{{ app_name }}'
python_bin: '{{ venv_dir }}/bin/python'
gunicorn_bin: '{{ venv_dir }}/bin/gunicorn'

# Django admin user
api_admin_user: '{{ deployer_user }}'
api_admin_password: <your-admin-password>
api_admin_email: <your-admin-email>

# Celery variables
celery_bin: '{{ venv_dir }}/bin/celery'
celery_log_level: INFO
celerybeat_pid_file: /var/run/celery/beat.pid
celerybeat_log_file: /var/log/celery/beat.log

# Server
server_ip: <your-server-ip>
secret_key: <your-secret-key>


