##
# Update the APT package cache and install packages as a root user
##
- name: Install required packages
  apt:
    state: present
    name:
    - build-essential # Required by weasyprint
    - libcairo2 # Required by weasyprint
    - libpango-1.0-0  # Required by weasyprint
    - libpangocairo-1.0-0  # Required by weasyprint
    - libgdk-pixbuf2.0-0  # Required by weasyprint
    - libffi-dev  # Required by weasyprint
    - shared-mime-info  # Required by weasyprint
    - python3-setuptools
    - python3-wheel
    - python3-dev
    - python3-pip
    - python3-cffi
    - python3-virtualenv
    - python3-psycopg2 # Required for manage postgres
    - python3-boto3 # Required to download files from S3 buckets
    - python3-botocore # Required to download files from S3 buckets
    - unzip
    - acl # Access control list, required from grant some permissions
  become: yes

- name: Create app directory
  file:
    path: '{{ app_dir }}'
    state: directory

- name: Create app api directory
  file:
    path: '{{ app_api_dir }}'
    state: directory

- name: Create app spa directory
  file:
    path: '{{ app_spa_dir }}'
    state: directory

- name: Create venv directory
  file:
    path: '{{ venv_root }}'
    state: directory

- name: Create libs directory
  file:
    path: '{{ libs_dir }}'
    state: directory

- name: Create the enviroment file for django
  template:
    src: .env.prod
    dest: '{{ env_file }}'
  become: yes

