##
# Download SPA dist files
##

- name: Download spa dist
  aws_s3:
    bucket: '{{ aws_bucket_name }}'
    object: '{{ spa_file_name }}'
    dest: '{{ app_spa_dir }}/{{ spa_file_name }}'
    aws_access_key: '{{ aws_access_key }}'
    aws_secret_key: '{{ aws_secret_key }}'
    mode: get


- name: Uncompress spa dist
  unarchive:
    src: '{{ app_spa_dir }}/{{ spa_file_name }}'
    dest: '{{ app_spa_dir }}'
    remote_src: yes
