##
# Run db migrations and get all static files
##
- name: Make migrations
  shell:
    cmd: 'set -a; . {{ env_file }}; set +a; {{ python_bin }} manage.py makemigrations --noinput'
    chdir: '{{ app_api_dir }}'

- name: Migrate database
  shell:
    cmd: 'set -a; . {{ env_file }}; set +a; {{ python_bin }} manage.py migrate --noinput'
    chdir: '{{ app_api_dir }}'

- name: Create admin account (optional)
  shell:
    cmd: >
      set -a; . {{ env_file }}; set +a;
      {{ python_bin }} manage.py createadmin
      {{ api_admin_user }} {{ api_admin_password }} {{ api_admin_email }}
    chdir: '{{ app_api_dir }}'
  when:
    - api_admin_user is defined
    - api_admin_password is defined
    - api_admin_email is defined

- name: Create exportings templates
  shell:
    cmd: >
      set -a; . {{ env_file }}; set +a;
      {{ python_bin }} manage.py create_exportings
    chdir: '{{ app_api_dir }}'

- name: Create labels templates
  shell:
    cmd: >
      set -a; . {{ env_file }}; set +a;
      {{ python_bin }} manage.py create_labels
    chdir: '{{ app_api_dir }}'

- name: Seed database confirm
  pause:
    prompt: 'Are you sure you want to SEED the project database "{{ db_name }}"? This action is IRREVERSIBLE. Press Ctrl+C to terminate if you are not sure of this.'
  when: run_dbseed

- name: Seed database with fixtures
  shell:
    cmd: >
      set -a; . {{ env_file }}; set +a;
      {{ python_bin }} manage.py dbseed
    chdir: '{{ app_api_dir }}'
  when: run_dbseed

- name: Get all static files
  shell:
    cmd: 'set -a; . {{ env_file }}; set +a; {{ python_bin }} manage.py collectstatic --noinput --clear'
    chdir: '{{ app_api_dir }}'
