##
# Set up Redis
##
- name: Set up redis
  apt: name=redis-server state=latest
  become: yes

- name: Set default config
  copy:
    remote_src: yes
    src: /etc/redis/redis.conf
    dest: /etc/redis/default.conf
    force: no
  become: yes

- name: Set config
  template:
    src: redis.conf
    dest: /etc/redis/redis.conf
    mode: '644'
  become: yes

- name: Start and enable redis service
  service:
    name: redis
    enabled: yes
    state: started
  become: yes
