##
# SSL with certbot
##
- name: Add certbot repository
  apt_repository:
    repo: ppa:certbot/certbot
    state: present
  become: yes

- name: Install certbot
  apt:
    state: latest
    name:
      - python-certbot-nginx
  become: yes

- name: Obtain
  shell:
    cmd: 'set -a; . {{ env_file }}; set +a; {{ python_bin }} manage.py collectstatic --noinput --clear'
    chdir: '{{ app_api_dir }}'
