##
# Configure the server for the Django app
##
- include: 01_server.yml
- include: 02_git.yml
- include: 03_dependencies.yml
- include: 04_postgres.yml
- include: 05_build_spa.yml
  when: build_spa
- include: 05_get_spa.yml
  when: get_spa
- include: 06_migrations.yml
- include: 07_nginx.yml
- include: 08_gunicorn.yml
- include: 09_redis.yml
  when: celery_enable
- include: 10_celery.yml
  when: celery_enable
- include: 11_restart.yml
